### ISSUE TITLE
2 Short questions

### ISSUE THREAD

**Issue by tHr4sh3R** [trythrow/simpleSlider#2]
Simple question - is it possible to loop the slideshow?
If yes, how? (my js skills are really bad :3)

2nd: I wanted to make the slideshow 100% width and height, width works, height makes the whole slider disappear. Why is that?

**Comment by trythrow** [comment]
Hello, there is no support for loop/autostart yet
as for the height, try "auto" instead of 100% and it will take the height from parent div

**Comment by tHr4sh3R** [comment]
Thanks for the fast reply.
If the parent div also has a %-height, the slider still completely disappears when setting "auto" :/

**Comment by trythrow** [comment]
Hi,

there is always a way which require some js, why not use fixed height?

You can also add this somehwere in your page

```
<script type="text/javascript">
$(document).ready(function(){
   $("#myslider").height( $(this).parent("div").height() );
});
</script>
```

Change "myslider" to whatever you slider div ID is, that will set the height of your slider based on parent div height

**Comment by tHr4sh3R** [comment]
I found another awesome solution:
 height:100vh;
for vertical height.

Works perfect!

(vw would be the tag for width)
